[project]
name = "cpppo"
version = "4.2.0"
description = "Communications Protocol Python Parser and Originator -- EtherNet/IP CIP"
authors = [
    {name = "Author"}
]
readme = "README.org"
requires-python = ">=3.8"
poetry = ">2.1.0"
dependencies = [
    "greenery (>=2.0,<3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
